repository: SwedbankPay/developer.swedbankpay.com
remote_theme: SwedbankPay/swedbank-pay-design-guide-jekyll-theme
exclude: ["Gemfile*", "Rakefile"]
plugins:
  - "jekyll-github-metadata"
defaults:
  - values:
      layout: default
      design_guide:
        base_url: https://design.swedbankpay.com
        version_url: https://design.swedbankpay.com/v/4.1.0
      topbar:
        navigation:
        - url: /checkout/
          title: Checkout
        - url: /payments/
          title: Payments
      sidebar:
        search:
          enabled: true
        navigation:
          - title: Checkout
            items:
            - url: /checkout/
              title: Side 1
            - url: /page2
              title: Side 2
          - title: Payments
            items:
            - url: /page1
              title: Side 3
            - url: /page2
              title: Side 4
