repository: SwedbankPay/developer.swedbankpay.com
remote_theme: SwedbankPay/swedbank-pay-design-guide-jekyll-theme
exclude: ["Gemfile*", "Rakefile"]
plugins:
  - "jekyll-github-metadata"
  - jemoji
tipue_search:
  include:
    pages: true
opengraph:
  description: Swedbank Pay Developer Portal
  image: /assets/img/swedbank-pay-developer-portal.png
design_guide:
  base_url: https://design.swedbankpay.com
  version: 4.1.0
search:
  enabled: true
  url: /search
topbar:
  navigation:
  - url: /checkout/
    title: Checkout
  - url: /payments/
    title: Payments
  - url: /resources/
    title: Resources
defaults:
  - values:
      layout: default
      paymentId: 7E6CDFC3-1276-44E9-9992-7CF4419750E1
      transactionId: EC2A9B09-601A-42AE-8E33-A5737E1CF177
      paymentOrderId: 09ccd29a-7c4f-4752-9396-12100cbfecce
